/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    level?: ("unknown" | number) | ("unknown" | number)[];
                    from?: string;
                    to?: string;
                    service?: string;
                    q?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    service?: string;
                    severity?: ("unknown" | number) | ("unknown" | number)[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/error-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorRateResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/new-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Issues first seen within the window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewIssuesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Issues ranked by event count within the window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopIssuesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/spikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpikesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/by-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ByServiceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportListResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateImportResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LogListQuery: {
            level?: ("unknown" | number) | ("unknown" | number)[];
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            service?: string;
            q?: string;
            /** @default 50 */
            limit: number;
            cursor?: string;
        };
        LogRecord: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            observedAt: string;
            severityNumber: number | null;
            severityText: string | null;
            body: string;
            serviceName: string | null;
            host: string | null;
            environment: string | null;
            traceId: string | null;
            spanId: string | null;
            sourceType: string;
            fingerprint: string;
        };
        LogListResponse: {
            records: components["schemas"]["LogRecord"][];
            nextCursor: string | null;
        };
        IssueListQuery: {
            service?: string;
            severity?: ("unknown" | number) | ("unknown" | number)[];
        };
        IssueListResponse: {
            issues: {
                fingerprint: string;
                sampleMessage: string;
                severityNumber: number | null;
                eventCount: number;
                /** Format: date-time */
                firstSeen: string;
                /** Format: date-time */
                lastSeen: string;
                affectedServices: string[];
                /** @enum {string} */
                status: "unresolved" | "resolved" | "ignored";
                regression: boolean;
            }[];
        };
        CreateImportResponse: {
            /** Format: uuid */
            id: string;
        };
        ImportStatusResponse: {
            /** Format: uuid */
            id: string;
            filename: string;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed";
            sourceType: string | null;
            totalLines: number | null;
            processedLines: number;
            parseErrors: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            error: string | null;
            result: {
                ingestedRecords: number;
                elapsedMs: number;
                linesPerSecond: number;
            } | null;
        };
        ImportListResponse: {
            imports: {
                /** Format: uuid */
                id: string;
                filename: string;
                /** @enum {string} */
                status: "pending" | "running" | "completed" | "failed";
                /** Format: date-time */
                createdAt: string;
                totalLines: number | null;
                processedLines: number;
                parseErrors: number;
            }[];
        };
        ErrorRateResponse: {
            buckets: {
                /** Format: date-time */
                bucket: string;
                total: number;
                errors: number;
                ratio: number;
            }[];
        };
        /** @description Issues first seen within the window */
        NewIssuesResponse: {
            issues: {
                fingerprint: string;
                sampleMessage: string;
                severity: number | null;
                eventCount: number;
                /** Format: date-time */
                firstSeen: string;
                services: string[];
            }[];
        };
        /** @description Issues ranked by event count within the window */
        TopIssuesResponse: {
            issues: {
                fingerprint: string;
                sampleMessage: string;
                severity: number | null;
                eventCount: number;
                /** Format: date-time */
                firstSeen: string;
                services: string[];
            }[];
        };
        SpikesResponse: {
            issues: {
                fingerprint: string;
                sampleMessage: string;
                severity: number | null;
                eventCount: number;
                /** Format: date-time */
                firstSeen: string;
                services: string[];
                currentCount: number;
                previousCount: number;
                multiplier: number;
            }[];
        };
        ByServiceResponse: {
            services: {
                serviceName: string;
                total: number;
                errors: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
